#!/usr/bin/env python3

from pathlib import Path
import sys

module_to_migrate = sys.argv[1]
community_path = Path(sys.argv[2])
amazon_path = Path(sys.argv[3])

ignore_dir = community_path / "tests" / "sanity"
ignore_dir.mkdir(parents=True, exist_ok=True)

for version in ["2.14", "2.15", "2.16", "2.17", "2.18", "2.19"]:
    to_be_removed = []
    ignore_file = ignore_dir / f"ignore-{version}.txt"
    ignore_content = ignore_file.read_text().split("\n")
    _ignore_content = ignore_content.copy()
    _ignore_content = list(filter(None, ignore_content))

    for line in ignore_content:
        if module_to_migrate in line:
            to_be_removed.append(line)
            _ignore_content.remove(line)
    
    if to_be_removed:
        ignore_file.write_text("\n".join(_ignore_content).lstrip("\n"))
        ignore_dir = amazon_path / "tests" / "sanity"
        ignore_dir.mkdir(parents=True, exist_ok=True)
        ignore_file = ignore_dir / f"ignore-{version}.txt"
        ignore_content = ignore_file.read_text().split("\n")
        ignore_content = list(filter(None, ignore_content))
        ignore_content.extend(to_be_removed)
        ignore_file.write_text("\n".join(ignore_content).lstrip("\n"))
    

